### PR TITLE
Small utility to remove fastq records

### PR DESCRIPTION
**Pull request by eclarke**
I frequently run into situations where I'd like to filter a fastq file to remove particular records (mostly during quality control and decontamination). It'd be nice to have a fast, consistent utility to do this (especially one on bioconda, and not in an interpreted language). 

If this is something worth adding, let me know what else I can do to firm it up, or if this is too small/basic for what you were envisioning, that's fine too.

### CODE REVIEW

**Comment by johanneskoester** [comment]
Nice! Almost perfect. Can you add a test to `tests/lib.rs`, analogous to what is already there?

**Comment by eclarke** [comment]
Great, thanks! I've added a small test, but now an unrelated test fails on this fork: 
In test vcf_match:
``` 
tests/matching.bcf tests/expected/matching.bcf differ: byte 17, line 1
```
I'm not sure what's happened here- did I break something, or did a dependency change?

**Comment by johanneskoester** [comment]
Not your fault, I think it fails because you have update the version number. I need to make this test independent of the version number. As I anyway want to increase the minor version on the next release (because a tool was added, semantic versioning), can you please remove the version increase? Then, tests should pass and I can fix the problem after the merge.

**Comment by eclarke** [comment]
Great, thanks! I'm happy to update the bioconda recipe as soon as you issue a new release

**Comment by johanneskoester** [comment]
Ok, new release is out. That would be great if you could update it on bioconda!

**Pull request merged**
