### PR TITLE
Add cargo install instructions

### PR DESCRIPTION
**Pull request by rhagenson**
Add standard cargo install instructions and differentiate this from installing via cargo from source

### CODE REVIEW

**Comment by rhagenson** [comment]
CI failure is unrelated to my PR. Failure was due to:

```bash
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
```

**Comment by johanneskoester** [comment]
Thank you! I need to find the time to switch from travis to github actions.

**Comment by rhagenson** [comment]
@johanneskoester, you're welcome!

On the topic of switching from Travis to GitHub Actions, I am not too familiar with Actions, so I imagine a translation of `.travis.yml` to Actions' equivalent and changing the README badge is what would be needed from a source perspective then linking/enabling Actions from the backend (by you) to kick it off? Speaking of, looking at `.travis.yml` right now it does not appear to have a `script` section so the CI failure/timeout is from not running test at all it seems?

**Comment by rhagenson** [comment]
I noticed in Travis' docs after making my above comment that there is a default `cargo test --verbose` command they run. If I worked on the translation to Actions I would make the testing explicit as a bit of future-proofing to avoid the service changing defaults from what we intend to run.

**Pull request merged**
