### PR TITLE
feat: Add UPGMA, Neighbor-Joining, and RF-distance to cli tool

### PR DESCRIPTION
**Pull request by RagnarGrootKoerkamp**
Depends on https://github.com/rust-bio/rust-bio/pull/470

This adds CLI wrappers for the algorithms added in that PR.

I could move the code in `main.rs` into a separate module, but it's so small that's probably not worth it.

### CODE REVIEW

**Review by johanneskoester — CHANGES_REQUESTED** [review]
Thanks a lot! I think having a separate module with the API calls for the two methods would be nice in order to keep main.rs a bit cleaner, if you don't mind.

**Comment by RagnarGrootKoerkamp** [comment]
Done

**Review by johanneskoester — APPROVED** [review]

**Comment by johanneskoester** [comment]
There are some errors now.

**Comment by RagnarGrootKoerkamp** [comment]
Yes the errors are expected. We first need to merge the other PRs:
https://github.com/rust-bio/rust-bio-types/pull/35
https://github.com/rust-bio/rust-bio/pull/468
https://github.com/rust-bio/rust-bio/pull/469
https://github.com/rust-bio/rust-bio/pull/470

**Comment by RagnarGrootKoerkamp** [comment]
This was a small project that never went anywhere. I don't care for it anymore.
If someone wants to continue it feel free to reopen.

**Pull request closed without merging**
